### ISSUE TITLE
obsolete, but why?

### ISSUE THREAD

**Issue by gre** [johanneslumpe/react-native-keyboardevents#24]
Hi,

The README says 

```
As of react-native 0.11 this module is obsolete.
```

Can you explicit more, maybe at least with a link? or just some snippet code of the RN equivalent? 

Thanks

**Comment by johanneslumpe** [comment]
Obsolete because this has been implemented: https://github.com/facebook/react-native/blob/master/React/Base/RCTKeyboardObserver.m 

If you look at https://github.com/facebook/react-native/blob/2f6e7336cb96bf14d47554ae0db1836075ea809e/Libraries/Components/ScrollResponder.js#L440 you can see how it is being used.

**Comment by gre** [comment]
Ok thanks, but I think this should be written in the readme (because react-native don't have a doc yet for that feature)
