### ISSUE TITLE
Documented example causes "Cannot read property 'height' of undefined"

### ISSUE THREAD

**Issue by shatran** [johanneslumpe/react-native-keyboardevents#28]
Hi,
when running the example i get "Cannot read property 'height' of undefined" in 'keyboardWillShow'.
The solution for this is to add an `if (e.endCoordinates && e.endCoordinates.height)` so the function now looks like this:

```
  keyboardWillShow (e) {
    if (e.endCoordinates && e.endCoordinates.height) {
      let newSize = Dimensions.get('window').height - e.endCoordinates.height;
      this.setState({visibleHeight: newSize})
    }
  }
```

And BTW thanks for this project!

**Comment by johanneslumpe** [comment]
@shatran This has been reported before and is due to the fact that since 0.11 react-native implements keyboard events natively. Do not use this module for react-native >= 0.11. Their event names are identical to the ones in this module.

See https://github.com/johanneslumpe/react-native-keyboardevents/issues/25, https://github.com/johanneslumpe/react-native-keyboardevents/issues/24#issuecomment-142209519, https://github.com/johanneslumpe/react-native-keyboardevents/pull/26#issuecomment-143475141

**Comment by shatran** [comment]
@johanneslumpe i understand that this module is not needed for react-native >= 0.11, but in the docs you say "Now you can do something like the following: Example by GantMan" and then supply an example that causes an error. So people are trying to use that example (without using the module) and gets an error. I'm just saying the example should be changed for future users that's all.

**Comment by johanneslumpe** [comment]
@shatran Feel free to submit a PR for this :) I'm currently kind of busy (hence the fact that the example was a PR too..)

**Comment by shatran** [comment]
Sure no problems. PR #29.
